/* The Doomsday Protocol - the watch order itself.
 *
 * PARTS       the 94 core entries, in six parts
 * EXTENSIONS  the 27 optional entries, in five blocks
 * POSTERS     poster art per entry id (verified at build time)
 * COMPOSED    entry ids with no real poster, and their theme colour
 *
 * These are deliberately globals: app.js reads them from inside its IIFE.
 * This file must load BEFORE app.js.
 */

/* ============================================================
   DATA
   id     stable key for saved progress — never reuse or rename
   type   film | series | special | short
   run    minutes (films exact; series ≈ eps × typical length)
   tier   essential | recommended | optional
   tl     timeline sort key (9xxx = off-calendar / another universe)
   tlt    optional override label for the timeline column
   soon   true = not released yet
   ============================================================ */

var PARTS = [
{
  no:'Part I', title:'The Infinity Saga', sub:'Films only, 2008–2019',
  blurb:'Twenty-four films, one continuous arc, and the reason any of the rest works. There are no series in this part on purpose — the Marvel Television of that era is either excluded or optional, and folding it in here would double the runtime for almost no return.',
  items:[
  {id:'ironman',t:'Iron Man',y:2008,type:'film',run:126,tier:'essential',tl:2010,dir:'Jon Favreau',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'The founding text. Tony Stark is the absence Doomsday is built around — Robert Downey Jr. returns as Victor Von Doom, and that casting only lands if you have the original in your head.',
   intro:'Tony Stark, Pepper Potts, James Rhodes, Nick Fury, S.H.I.E.L.D.',
   note:'The post-credits scene is where the entire shared universe is announced. Do not skip it.'},
  {id:'hulk',t:'The Incredible Hulk',y:2008,type:'film',run:112,tier:'optional',tl:2011,dir:'Louis Leterrier',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'The odd one out, and the least loved. It matters now only because Samuel Sterns returned as The Leader in Brave New World, and because Emil Blonsky reappears in She-Hulk.',
   intro:'Bruce Banner (Edward Norton), Emil Blonsky / Abomination, Samuel Sterns, Thaddeus Ross',
   note:'Edward Norton plays Banner here and nowhere else. Mark Ruffalo takes over from The Avengers onward.'},
  {id:'ironman2',t:'Iron Man 2',y:2010,type:'film',run:124,tier:'optional',tl:2011.1,dir:'Jon Favreau',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Mostly setup for The Avengers. Introduces Natasha Romanoff and Justin Hammer, and sows the Vanko grudge that Armor Wars may still pick up.',
   intro:'Natasha Romanoff / Black Widow, Justin Hammer, Ivan Vanko'},
  {id:'thor',t:'Thor',y:2011,type:'film',run:115,tier:'recommended',tl:2011.2,dir:'Kenneth Branagh',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Establishes Asgard, the Nine Realms, and Loki — the character whose fate in his own series eventually decides how the multiverse is even shaped.',
   intro:'Thor, Loki, Odin, Heimdall, Jane Foster, Erik Selvig'},
  {id:'firstavenger',t:'Captain America: The First Avenger',y:2011,type:'film',run:124,tier:'essential',tl:1943,dir:'Joe Johnston',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Steve Rogers, Bucky Barnes, HYDRA and the Tesseract all start here. Sam Wilson carries the shield into Doomsday, and the weight of that only exists because of this film.',
   intro:'Steve Rogers, Bucky Barnes, Peggy Carter, Red Skull, the Tesseract'},
  {id:'avengers',t:'The Avengers',y:2012,type:'film',run:143,tier:'essential',tl:2012,dir:'Joss Whedon',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'The template Doomsday is deliberately echoing — the impossible roster assembled against a threat none of them can take alone. Also the first appearance of Thanos.',
   intro:'The Avengers as a team, Thanos, the Chitauri, the Battle of New York'},
  {id:'ironman3',t:'Iron Man 3',y:2013,type:'film',run:130,tier:'optional',tl:2012.9,dir:'Shane Black',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Tony after New York. Its lasting contribution is the Mandarin misdirection, which Shang-Chi later corrected and expanded.',
   intro:'Aldrich Killian, Trevor Slattery, Extremis'},
  {id:'darkworld',t:'Thor: The Dark World',y:2013,type:'film',run:112,tier:'optional',tl:2013,dir:'Alan Taylor',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Weakest link in the saga, but it puts the Aether — the Reality Stone — on the board, and it is where Loki fakes his death and takes Asgard’s throne.',
   intro:'The Aether / Reality Stone, the Collector'},
  {id:'wintersoldier',t:'Captain America: The Winter Soldier',y:2014,type:'film',run:136,tier:'essential',tl:2014,dir:'Anthony and Joe Russo',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'The Russo brothers’ first Marvel film and still their best. HYDRA hollows out S.H.I.E.L.D., Bucky comes back, and Sam Wilson arrives. Directors of Doomsday, characters in Doomsday.',
   intro:'Sam Wilson / Falcon, the Winter Soldier, Sharon Carter, Alexander Pierce'},
  {id:'gotg',t:'Guardians of the Galaxy',y:2014,type:'film',run:121,tier:'recommended',tl:2014.1,dir:'James Gunn',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Opens the cosmic side of the map and introduces the Nova Corps, the Kree, and Thanos’s daughters.',
   intro:'Star-Lord, Gamora, Drax, Rocket, Groot, Nebula, Ronan, the Power Stone'},
  {id:'gotg2',t:'Guardians of the Galaxy Vol. 2',y:2017,type:'film',run:136,tier:'optional',tl:2014.2,dir:'James Gunn',where:'Disney+ / JioHotstar (IN)',pc:5,
   why:'Placed here because it happens only months after the first film. Introduces Mantis and Adam Warlock’s creation, and gives Rocket and Nebula the groundwork Vol. 3 pays off.',
   intro:'Mantis, Ego, Ayesha, the Sovereign',
   note:'Watched out of release order on purpose — it sits between the first film and Age of Ultron chronologically.'},
  {id:'ultron',t:'Avengers: Age of Ultron',y:2015,type:'film',run:141,tier:'essential',tl:2015,dir:'Joss Whedon',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Vision and Wanda both begin here, and Vision’s creation is the thread VisionQuest pulls on directly. The team fracture that becomes Civil War starts in this film too.',
   intro:'Vision, Wanda Maximoff, Pietro Maximoff, Ultron, Ulysses Klaue'},
  {id:'antman',t:'Ant-Man',y:2015,type:'film',run:117,tier:'recommended',tl:2015.1,dir:'Peyton Reed',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'The Quantum Realm is introduced here, and it becomes the mechanism for Endgame’s time heist and Kang’s arrival.',
   intro:'Scott Lang, Hope van Dyne, Hank Pym, the Quantum Realm'},
  {id:'civilwar',t:'Captain America: Civil War',y:2016,type:'film',run:147,tier:'essential',tl:2016,dir:'Anthony and Joe Russo',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'The Avengers break, and they never fully mend. Also the debut of both T’Challa and Tom Holland’s Peter Parker, and the first appearance of Helmut Zemo.',
   intro:'Black Panther, Spider-Man (Holland), Zemo, the Sokovia Accords'},
  {id:'blackwidow',t:'Black Widow',y:2021,type:'film',run:134,tier:'recommended',tl:2016.1,dir:'Cate Shortland',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Set immediately after Civil War. Introduces Yelena Belova and Alexei Shostakov, both now core Thunderbolts, and Valentina Allegra de Fontaine, who is assembling that team.',
   intro:'Yelena Belova, Red Guardian, Melina, Taskmaster, Valentina',
   stop:'Stop before the post-credits scene. It takes place years later, after Endgame, and it sets up Hawkeye. Come back to it when you reach Hawkeye in Part III.'},
  {id:'drstrange',t:'Doctor Strange',y:2016,type:'film',run:115,tier:'essential',tl:2016.5,dir:'Scott Derrickson',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Magic, the Time Stone, and the multiverse’s first proper description. Every rule Doomsday will bend was written down in this film.',
   intro:'Stephen Strange, Wong, Mordo, the Ancient One, the Time Stone, the Dark Dimension'},
  {id:'homecoming',t:'Spider-Man: Homecoming',y:2017,type:'film',run:133,tier:'recommended',tl:2016.4,dir:'Jon Watts',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Peter’s own film, and the source of the Vulture and the Damage Control angle that Marvel keeps returning to.',
   intro:'Adrian Toomes / Vulture, Ned, MJ, Happy as handler'},
  {id:'ragnarok',t:'Thor: Ragnarok',y:2017,type:'film',run:130,tier:'recommended',tl:2017,dir:'Taika Waititi',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Asgard falls, Valkyrie and Korg arrive, and the film ends on the shot Infinity War opens with. Watching them apart is the wrong choice.',
   intro:'Valkyrie, Korg, Hela, the Grandmaster, Sakaar'},
  {id:'blackpanther',t:'Black Panther',y:2018,type:'film',run:134,tier:'recommended',tl:2017.1,dir:'Ryan Coogler',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Wakanda in full, Shuri’s mind, and the vibranium that half the franchise now runs on.',
   intro:'Shuri, Okoye, Nakia, Killmonger, M’Baku, Everett Ross in Wakanda'},
  {id:'infinitywar',t:'Avengers: Infinity War',y:2018,type:'film',run:149,tier:'essential',tl:2018,dir:'Anthony and Joe Russo',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'The Russos’ first half of the endgame, and the proof they can hold thirty characters in one film — exactly the problem Doomsday sets them again.',
   intro:'Thanos in full, the Black Order, the Snap'},
  {id:'antman2',t:'Ant-Man and the Wasp',y:2018,type:'film',run:118,tier:'optional',tl:2018.1,dir:'Peyton Reed',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Runs parallel to Infinity War. Its only load-bearing moment is the post-credits scene, which strands Scott in the Quantum Realm and directly causes Endgame.',
   intro:'Janet van Dyne, Ghost, Bill Foster',
   note:'Placed after Infinity War deliberately — its post-credits scene only makes sense once you know the Snap happened.'},
  {id:'captainmarvel',t:'Captain Marvel',y:2019,type:'film',run:123,tier:'recommended',tl:1995,dir:'Anna Boden and Ryan Fleck',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'A 1995 flashback dropped here on purpose, to explain Fury’s pager the moment before Endgame answers it. Also the Skrulls, which Secret Invasion later escalates.',
   intro:'Carol Danvers, Talos and the Skrulls, Goose, young Fury and Coulson'},
  {id:'endgame',t:'Avengers: Endgame',y:2019,type:'film',run:181,tier:'essential',tl:2018.5,dir:'Anthony and Joe Russo',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The five-year gap, the branched timelines, and the death of Tony Stark. Everything about the multiverse’s current mess traces back to the time heist in this film.',
   intro:'The Blip, branched realities, Sam receiving the shield',
   note:'A recut theatrical version, Endgame Encore, is the final entry on this list. This is still the version the plot depends on.'},
  {id:'farfromhome',t:'Spider-Man: Far From Home',y:2019,type:'film',run:129,tier:'recommended',tl:2024,dir:'Jon Watts',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'The world immediately after Endgame, and the mid-credits reveal that upends Peter’s life and starts No Way Home.',
   intro:'Mysterio, Nick Fury’s absence explained, Peter’s identity exposed'}
]},

{
  no:'Part II', title:'The Street-Level Track', sub:'Required before Born Again',
  blurb:'The single biggest time investment on this list — roughly seventy hours of New York crime drama, made for Netflix between 2015 and 2019 and quietly folded back into canon. Daredevil: Born Again is a continuation of this, not a reboot, and Born Again matters to Doomsday. If you are short on time, Daredevil Seasons 1 and 3 plus The Punisher Season 1 carry most of the weight.',
  items:[
  {id:'dd1',t:'Daredevil — Season 1',y:2015,type:'series',eps:13,run:702,tier:'recommended',tl:2015.05,dir:'Drew Goddard (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Matt Murdock, Foggy, Karen and Wilson Fisk, all from zero. Born Again assumes every relationship established here.',
   intro:'Matt Murdock, Foggy Nelson, Karen Page, Wilson Fisk, Claire Temple'},
  {id:'jj1',t:'Jessica Jones — Season 1',y:2015,type:'series',eps:13,run:728,tier:'optional',tl:2015.15,dir:'Melissa Rosenberg (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The best-written season of the Netflix run, and the reason Jessica’s return would carry weight. Not strictly required for Born Again.',
   intro:'Jessica Jones, Trish Walker, Kilgrave, Luke Cage'},
  {id:'dd2',t:'Daredevil — Season 2',y:2016,type:'series',eps:13,run:715,tier:'recommended',tl:2016.05,dir:'Doug Petrie and Marco Ramirez',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Introduces Frank Castle and Elektra. Frank is on the Doomsday-adjacent board via his own 2026 special.',
   intro:'Frank Castle / The Punisher, Elektra Natchios, The Hand'},
  {id:'pun1',t:'The Punisher — Season 1',y:2017,type:'series',eps:13,run:715,tier:'optional',tl:2016.15,dir:'Steve Lightfoot (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Frank’s origin filled in, and Billy Russo’s turn. Useful before The Punisher: One Last Kill.',
   intro:'Billy Russo, Micro, Dinah Madani'},
  {id:'dd3',t:'Daredevil — Season 3',y:2018,type:'series',eps:13,run:715,tier:'recommended',tl:2018.05,dir:'Erik Oleson',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Fisk’s ascent to legitimacy — the exact position he occupies when Born Again begins. The most directly load-bearing season of the six.',
   intro:'Bullseye / Benjamin Poindexter, Fisk’s political turn'},
  {id:'pun2',t:'The Punisher — Season 2',y:2019,type:'series',eps:13,run:676,tier:'optional',tl:2018.15,dir:'Steve Lightfoot',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Closes Frank’s Netflix arc. Least essential of the six, and the easiest to cut if time is tight.',
   intro:'Jigsaw, Amy Bendix'}
]},

{
  no:'Part III', title:'The Multiverse Saga', sub:'Phases 4 and 5, 2021–2024',
  blurb:'Where the shared universe stops being one road and becomes a junction. This is also where the ordering stops being obvious: three entries here have to be interrupted mid-run, and two of them would spoil a film if you did not.',
  items:[
  {id:'wandavision',t:'WandaVision',y:2021,type:'series',eps:9,run:350,tier:'essential',tl:2024.1,dir:'Matt Shakman',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Wanda becomes the Scarlet Witch, Vision is rebuilt as White Vision, and Agatha Harkness arrives. VisionQuest is a direct sequel to this show’s final scenes.',
   intro:'Agatha Harkness, White Vision, Monica Rambeau, Darcy, the Darkhold’s pull'},
  {id:'tfatws',t:'The Falcon and the Winter Soldier',y:2021,type:'series',eps:6,run:300,tier:'recommended',tl:2024.2,dir:'Malcolm Spellman (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Sam earns the shield for real, John Walker becomes US Agent, and Zemo returns. Three Doomsday-relevant characters repositioned in six episodes.',
   intro:'John Walker / US Agent, Isaiah Bradley, Sharon as the Power Broker, Sam as Captain America'},
  {id:'loki1',t:'Loki — Season 1',y:2021,type:'series',eps:6,run:290,tier:'essential',tl:9000,dir:'Michael Waldron (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The Sacred Timeline, the TVA, and the branching that makes the multiverse a live problem instead of a theory. The single most important piece of homework on this list.',
   intro:'The TVA, Mobius, Sylvie, He Who Remains, Ravonna Renslayer',
   stop:'Stop at the end of Season 1. Season 2 comes much later, after Quantumania — watching it now removes the ground under several films in between.'},
  {id:'whatif1',t:'What If…? — Season 1',y:2021,type:'series',eps:9,run:300,tier:'recommended',tl:9100,dir:'Bryan Andrews',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Establishes the Watcher and shows what a divergent universe actually looks like — useful vocabulary before a film built entirely from them.',
   intro:'Uatu the Watcher, Captain Carter, Infinity Ultron, the Guardians of the Multiverse'},
  {id:'shangchi',t:'Shang-Chi and the Legend of the Ten Rings',y:2021,type:'film',run:132,tier:'recommended',tl:2024.3,dir:'Destin Daniel Cretton',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'The Ten Rings are still an unexplained signal at the end of this film, and Marvel has never closed that thread. Also corrects the Mandarin misdirection from Iron Man 3.',
   intro:'Shang-Chi, Katy, Xu Wenwu, the real Ten Rings'},
  {id:'eternals',t:'Eternals',y:2021,type:'film',run:156,tier:'optional',tl:2024.4,dir:'Chloé Zhao',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'The most self-contained MCU film. It stays on the list because the Celestials establish the scale at which the multiverse operates, and because Eros is a loose thread.',
   intro:'The Eternals, the Celestials, Arishem, Eros, Dane Whitman'},
  {id:'hawkeye15',t:'Hawkeye — Episodes 1–5',y:2021,type:'series',eps:5,run:210,tier:'recommended',tl:2024.5,dir:'Jonathan Igla (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Kate Bishop, Yelena in the present day, and the return of Kingpin to the film side of the universe.',
   intro:'Kate Bishop, Maya Lopez / Echo, Kingpin in the MCU proper',
   stop:'Watch Black Widow’s post-credits scene now, before episode 1 — it is what sends Yelena after Clint. Then stop after episode 5.'},
  {id:'nowayhome',t:'Spider-Man: No Way Home',y:2021,type:'film',run:148,tier:'essential',tl:2024.6,dir:'Jon Watts',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'The first time the MCU physically pulls people out of other universes. The mechanism Doomsday uses at scale is demonstrated here at small scale.',
   intro:'The Raimi and Webb Spider-Men, five returning villains, the world forgetting Peter Parker',
   note:'This film hits hardest if you have watched Part IV first. Hawkeye’s finale spoils its ending in passing, which is why the series is split around it.'},
  {id:'hawkeye6',t:'Hawkeye — Episode 6',y:2021,type:'series',eps:1,run:47,tier:'recommended',tl:2024.7,dir:'Rhys Thomas',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The finale, now safe to watch. Closes Kate and Clint’s arc and sets up Echo.',
   intro:'Kingpin and Maya’s confrontation'},
  {id:'moonknight',t:'Moon Knight',y:2022,type:'series',eps:6,run:290,tier:'optional',tl:2025,dir:'Jeremy Slater (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Almost entirely disconnected — Egyptian gods, dissociative identity, no Avengers. It is here because Marc Spector exists and Marvel has not forgotten him.',
   intro:'Marc Spector, Steven Grant, Jake Lockley, Khonshu, Layla / Scarlet Scarab'},
  {id:'mom',t:'Doctor Strange in the Multiverse of Madness',y:2022,type:'film',run:126,tier:'essential',tl:2025.1,dir:'Sam Raimi',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Incursions. The rule that two universes colliding destroys both is stated here, and it is the most likely engine of Doomsday’s plot.',
   intro:'America Chavez, the Illuminati, Earth-838, incursions, the Darkhold’s cost',
   note:'Watch WandaVision first without exception. This film is unreadable as a Wanda story otherwise.'},
  {id:'msmarvel',t:'Ms. Marvel',y:2022,type:'series',eps:6,run:290,tier:'optional',tl:2025.2,dir:'Bisha K. Ali (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Kamala Khan’s origin, and the reveal about her powers’ source — the MCU’s first on-screen use of the word mutant. Required if you intend to watch The Marvels.',
   intro:'Kamala Khan, the Clandestines, the Noor Dimension, the mutant reference'},
  {id:'lovethunder',t:'Thor: Love and Thunder',y:2022,type:'film',run:118,tier:'optional',tl:2025.3,dir:'Taika Waititi',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Divisive and largely self-contained. Leaves Hercules on the board and gives Thor a daughter, neither of which has been followed up.',
   intro:'Gorr, Mighty Thor, Zeus, Hercules, Love'},
  {id:'shehulk',t:'She-Hulk: Attorney at Law',y:2022,type:'series',eps:9,run:300,tier:'optional',tl:2025.4,dir:'Jessica Gao (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'A comedy that quietly parks several characters — Blonsky, Wong, Skaar and the Intelligencia — where later projects can collect them.',
   intro:'Jennifer Walters, Skaar, Titania, Daredevil in yellow'},
  {id:'werewolf',t:'Werewolf by Night',y:2022,type:'special',eps:1,run:52,tier:'optional',tl:2025.45,dir:'Michael Giacchino',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'A fifty-two-minute black-and-white monster movie, and the MCU’s first proper horror. It opens a corner of the universe — the monster-hunting world — that nothing else has followed up on, which is exactly why it costs you so little to watch.',
   intro:'Jack Russell / Werewolf by Night, Elsa Bloodstone, Man-Thing, the Bloodstone',
   note:'Shot in black and white with period film grain, and scored by its own director. There is a colour version on Disney+ too — watch the black-and-white one.'},
  {id:'wakandaforever',t:'Black Panther: Wakanda Forever',y:2022,type:'film',run:161,tier:'recommended',tl:2025.5,dir:'Ryan Coogler',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Shuri takes the mantle, and Namor and Talokan enter the map as a power that answers to nobody.',
   intro:'Namor, Talokan, Riri Williams, Shuri as Black Panther'},
  {id:'holidayspecial',t:'The Guardians of the Galaxy Holiday Special',y:2022,type:'special',eps:1,run:44,tier:'optional',tl:2025.55,dir:'James Gunn',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Forty-four minutes, and it does real work: it explains how the Guardians came to own Knowhere, which Vol. 3 opens by assuming you already know. Also the funniest thing in the MCU.',
   intro:'Kevin Bacon, Cosmo the Spacedog speaking, the Guardians’ new home',
   note:'Watch it before Vol. 3, not after. Vol. 3 gives you no recap at all.'},
  {id:'quantumania',t:'Ant-Man and the Wasp: Quantumania',y:2023,type:'film',run:124,tier:'recommended',tl:2026,dir:'Peyton Reed',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Kang the Conqueror in full, and the Council of Kangs. Marvel has since pivoted away from Kang toward Doom — this film is the clearest record of the road not taken.',
   intro:'Kang the Conqueror, MODOK, the Council of Kangs, Cassie as Stature'},
  {id:'loki2',t:'Loki — Season 2',y:2023,type:'series',eps:6,run:300,tier:'essential',tl:9001,dir:'Justin Benson and Aaron Moorhead',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The finale changes the physical shape of the multiverse. If you understand only one thing before Doomsday, make it what Loki does in the last fifteen minutes of this season.',
   intro:'Victor Timely, the Temporal Loom, Yggdrasil, Loki’s throne'},
  {id:'gotg3',t:'Guardians of the Galaxy Vol. 3',y:2023,type:'film',run:150,tier:'recommended',tl:2026.1,dir:'James Gunn',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'The end of that team as you knew it, and a genuinely great film. Doomsday relevance is modest — mainly which Guardians are still alive and where.',
   intro:'The High Evolutionary, Adam Warlock, Rocket’s past, the new Guardians roster'},
  {id:'secretinvasion',t:'Secret Invasion',y:2023,type:'series',eps:6,run:290,tier:'optional',tl:2026.2,dir:'Kyle Bradstreet (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Poorly received, but it changes Rhodey’s status in a way no other project has undone, and it hands Fury a rebuilt position off-world.',
   intro:'Gravik, G’iah, the Skrull colony, the Rhodey revelation'},
  {id:'marvels',t:'The Marvels',y:2023,type:'film',run:105,tier:'recommended',tl:2026.3,dir:'Nia DaCosta',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'The post-credits scene is the point: Monica wakes up in another universe, greeted by a Fox X-Men character. That is the connective tissue the X-Men homework exists for.',
   intro:'Dar-Benn, Monica stranded in another reality, Beast (Kelsey Grammer)'},
  {id:'echo',t:'Echo',y:2024,type:'series',eps:5,run:220,tier:'optional',tl:2025.6,dir:'Sydney Freeland',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Maya’s solo run, and the bridge between Hawkeye’s Kingpin and Born Again’s. Its post-credits scene points straight at Born Again.',
   intro:'Maya’s ancestry and powers, Fisk’s mayoral ambition'}
]},

{
  no:'Part IV', title:'The Older Universes', sub:'Blade, Ghost Rider, and every live-action Spider-Man before Holland',
  blurb:'Marvel films from before there was an MCU. The two Spider-Man runs earn their place outright — No Way Home put both on screen and made them canonical universes, and that film lands completely differently if you have actually met these people. Blade and Ghost Rider are softer calls, kept short and tagged Optional: Blade because the 1998 film is the reason modern comic-book cinema exists and an MCU Blade is still in development, Ghost Rider because a new one with Ryan Gosling is announced for 2028.',
  items:[
  {id:'blade1',t:'Blade',y:1998,type:'film',run:120,tier:'optional',tl:9500,tlt:'Unassigned universe',dir:'Stephen Norrington',where:'Disney+ / JioHotstar, or rental',pc:0,
   why:'The film that proved a Marvel property could work on screen, two years before X-Men and a decade before Iron Man. Wesley Snipes’ Blade is still the benchmark the delayed MCU version is measured against.',
   intro:'Blade, Whistler, Deacon Frost, the vampire underworld'},
  {id:'blade2',t:'Blade II',y:2002,type:'film',run:117,tier:'optional',tl:9501,tlt:'Unassigned universe',dir:'Guillermo del Toro',where:'Disney+ / JioHotstar, or rental',pc:0,
   why:'The best of the three, and the one most often cited as an influence on how Marvel horror should look. Optional, but if you watch one Blade film, consider making it this one.',
   intro:'The Bloodpack, the Reapers, Nomak'},
  {id:'blade3',t:'Blade: Trinity',y:2004,type:'film',run:113,tier:'optional',tl:9502,tlt:'Unassigned universe',dir:'David S. Goyer',where:'Disney+ / JioHotstar, or rental',pc:0,
   why:'The weakest by a distance, and famously troubled behind the camera. On the list for completeness — it introduces Hannibal King and Abigail Whistler, and it is where the trilogy stops.',
   intro:'Hannibal King, Abigail Whistler, Dracula / Drake'},
  {id:'ghostrider1',t:'Ghost Rider',y:2007,type:'film',run:114,tier:'optional',tl:9510,tlt:'Unassigned universe',dir:'Mark Steven Johnson',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:0,
   why:'Nicolas Cage as Johnny Blaze. Not good, and not connected to anything — but it is the character’s only live-action feature run before Shawn Levy’s 2028 film.',
   intro:'Johnny Blaze, Mephistopheles, Blackheart, Carter Slade'},
  {id:'ghostrider2',t:'Ghost Rider: Spirit of Vengeance',y:2011,type:'film',run:95,tier:'optional',tl:9511,tlt:'Unassigned universe',dir:'Neveldine and Taylor',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:0,
   why:'A stranger, cheaper, more unhinged sequel. Included only so the Ghost Rider block is complete. Skipping it costs you nothing.',
   intro:'A harder-edged Blaze, Danny Ketch as a boy',
   note:'If you want a genuinely good live-action Ghost Rider, it is Robbie Reyes in Agents of S.H.I.E.L.D. Season 4 — see the exclusions section below.'},
  {id:'spidey1',t:'Spider-Man',y:2002,type:'film',run:121,tier:'recommended',tl:9520,tlt:'Earth-96283',dir:'Sam Raimi',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:0,
   why:'Tobey Maguire’s Peter, and the film that started the modern superhero boom. No Way Home confirmed this universe as real, and Raimi went on to direct Multiverse of Madness.',
   intro:'Tobey Maguire’s Peter Parker, Norman Osborn / Green Goblin, Uncle Ben, MJ Watson'},
  {id:'spidey2',t:'Spider-Man 2',y:2004,type:'film',run:127,tier:'recommended',tl:9521,tlt:'Earth-96283',dir:'Sam Raimi',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:0,
   why:'Widely held to be the best Spider-Man film ever made, and the source of Doc Ock — who returns in No Way Home with this exact history intact.',
   intro:'Otto Octavius / Doctor Octopus, the fusion reactor, Peter quitting'},
  {id:'spidey3',t:'Spider-Man 3',y:2007,type:'film',run:139,tier:'optional',tl:9522,tlt:'Earth-96283',dir:'Sam Raimi',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:0,
   why:'Overstuffed and much mocked, but it closes the trilogy and introduces Sandman, who also returns in No Way Home. The symbiote here is unrelated to Sony’s Venom films.',
   intro:'Flint Marko / Sandman, Eddie Brock, the symbiote, Harry as the New Goblin'},
  {id:'tasm1',t:'The Amazing Spider-Man',y:2012,type:'film',run:136,tier:'recommended',tl:9530,tlt:'Earth-120703',dir:'Marc Webb',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:1,
   why:'Andrew Garfield’s Peter and Gwen Stacy. His return in No Way Home is the emotional centre of that film, and it only works if you know what happened to Gwen.',
   intro:'Andrew Garfield’s Peter Parker, Gwen Stacy, Curt Connors / The Lizard'},
  {id:'tasm2',t:'The Amazing Spider-Man 2',y:2014,type:'film',run:142,tier:'recommended',tl:9531,tlt:'Earth-120703',dir:'Marc Webb',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:1,
   why:'The film No Way Home directly reaches back into. Whatever you think of the rest of it, its ending is the reason Garfield’s scenes in that film land the way they do.',
   intro:'Max Dillon / Electro, Harry Osborn / Green Goblin, Gwen’s fate',
   note:'Watch this before No Way Home in Part III, not after. The order matters more here than almost anywhere else on this list.'}
]},

{
  no:'Part V', title:'The X-Men', sub:'The complete Fox catalogue, 2000–2024',
  blurb:'Every X-Men project Fox made, plus the animated revival Marvel Studios produced. Doomsday’s announced cast reaches back into this universe, so the whole catalogue is listed rather than a curated handful — tiered honestly, so you can see at a glance which four actually carry weight and which are here for completeness. The order below is a watch order, not release order: the original trilogy first, then the prequel branch, then the endpoints.',
  items:[
  {id:'xmen1',t:'X-Men',y:2000,type:'film',run:104,tier:'recommended',tl:9200,tlt:'Earth-10005',dir:'Bryan Singer',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The foundation of the Fox universe. Establishes Xavier, Magneto, and the mutant-persecution premise Doomsday is expected to import wholesale.',
   intro:'Professor X, Magneto, Wolverine, Storm, Cyclops, Jean Grey, Rogue, Mystique'},
  {id:'x2',t:'X2: X-Men United',y:2003,type:'film',run:134,tier:'recommended',tl:9201,tlt:'Earth-10005',dir:'Bryan Singer',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The best of the original trilogy, and the film that turns Jean Grey into the Phoenix problem.',
   intro:'William Stryker, Nightcrawler, Jean’s sacrifice'},
  {id:'x3',t:'X-Men: The Last Stand',y:2006,type:'film',run:104,tier:'optional',tl:9202,tlt:'Earth-10005',dir:'Brett Ratner',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Weak, but Days of Future Past spends its running time undoing it, and you cannot feel that undoing without having seen this.',
   intro:'Dark Phoenix, the mutant cure, Beast in the cabinet'},
  {id:'origins',t:'X-Men Origins: Wolverine',y:2009,type:'film',run:107,tier:'optional',tl:9203,tlt:'Earth-10005',dir:'Gavin Hood',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'The worst-regarded film in the franchise, and Deadpool &amp; Wolverine spends a running gag on saying so. Its only lasting contribution is Logan’s backstory and the Weapon X programme.',
   intro:'Victor Creed / Sabretooth, Weapon X, the version of Wade Wilson everyone pretends did not happen'},
  {id:'firstclass',t:'X-Men: First Class',y:2011,type:'film',run:132,tier:'recommended',tl:9204,tlt:'Earth-10005',dir:'Matthew Vaughn',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The 1962 reboot-within-a-franchise, and a genuinely excellent film. Recasts Xavier and Magneto as McAvoy and Fassbender, which is the version the later films run on.',
   intro:'Young Charles and Erik, Sebastian Shaw, Emma Frost, the Cuban Missile Crisis'},
  {id:'wolverine2013',t:'The Wolverine',y:2013,type:'film',run:126,tier:'optional',tl:9205,tlt:'Earth-10005',dir:'James Mangold',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Logan in Japan, after The Last Stand. Mangold’s first pass at the character before he made Logan, and its post-credits scene leads straight into Days of Future Past.',
   intro:'Yukio, Mariko, the Silver Samurai, Logan grieving Jean'},
  {id:'dofp',t:'X-Men: Days of Future Past',y:2014,type:'film',run:132,tier:'recommended',tl:9206,tlt:'Earth-10005',dir:'Bryan Singer',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'A time-travel reset that proves the Fox timeline can be rewritten — precedent that matters in a film about universes being rearranged. Also the only film with both casts together.',
   intro:'Sentinels, Quicksilver (Evan Peters), the rewritten timeline'},
  {id:'apocalypse',t:'X-Men: Apocalypse',y:2016,type:'film',run:144,tier:'optional',tl:9207,tlt:'Earth-10005',dir:'Bryan Singer',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'The 1980s instalment. Introduces the younger Cyclops, Jean and Storm, and Apocalypse himself. Little of it carries forward.',
   intro:'En Sabah Nur / Apocalypse, young Jean Grey, young Scott Summers, Psylocke'},
  {id:'darkphoenix',t:'Dark Phoenix',y:2019,type:'film',run:113,tier:'optional',tl:9208,tlt:'Earth-10005',dir:'Simon Kinberg',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The final Fox X-Men ensemble film, released as the Disney acquisition closed. A second attempt at the Phoenix story that landed no better than the first. On the list for completeness only.',
   intro:'Jean as Phoenix, the D’Bari, the end of the Fox mainline'},
  {id:'newmutants',t:'The New Mutants',y:2020,type:'film',run:94,tier:'optional',tl:9209,tlt:'Earth-10005',dir:'Josh Boone',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Shot in 2017, released in 2020 after years of delays. A haunted-house film with mutants. Genuinely disconnected from everything, and the true end of the Fox era.',
   intro:'Dani Moonstar, Wolfsbane, Magik, Cannonball, Sunspot'},
  {id:'logan',t:'Logan',y:2017,type:'film',run:137,tier:'essential',tl:9215,tlt:'Earth-10005 · 2029',dir:'James Mangold',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Hugh Jackman’s ending, and Deadpool &amp; Wolverine builds its entire premise on respecting it. Also introduces Laura, who Marvel has openly kept in play.',
   intro:'Laura / X-23, the death of Logan, Charles’s decline',
   note:'Placed here rather than in release order because it is set in 2029 — the far end of the Fox timeline, after everything above it.'},
  {id:'deadpool1',t:'Deadpool',y:2016,type:'film',run:108,tier:'recommended',tl:9220,tlt:'Earth-10005',dir:'Tim Miller',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Wade Wilson’s origin, done properly this time. Deadpool &amp; Wolverine assumes all of it, and Doomsday assumes Deadpool &amp; Wolverine.',
   intro:'Deadpool, Vanessa, Colossus, Negasonic Teenage Warhead, Ajax'},
  {id:'deadpool2',t:'Deadpool 2',y:2018,type:'film',run:119,tier:'optional',tl:9221,tlt:'Earth-10005',dir:'David Leitch',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Cable and Domino arrive, and the time-travel post-credits gag becomes retroactively relevant. Optional, but short and painless.',
   intro:'Cable, Domino, X-Force, Russell / Firefist'},
  {id:'dpw',t:'Deadpool &amp; Wolverine',y:2024,type:'film',run:128,tier:'essential',tl:9222,tlt:'Earth-10005 → MCU',dir:'Shawn Levy',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'The hinge. It formally connects the Fox universe to the MCU, brings the TVA back into the film side, and establishes the Void and anchor beings. Do not skip this one.',
   intro:'Cassandra Nova, the Void, anchor beings, the Fox universe’s canonical status'},
  {id:'legion',t:'Legion',y:2017,type:'series',eps:27,run:1350,tier:'optional',tl:9240,tlt:'Earth-10005 (loosely)',dir:'Noah Hawley (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Three seasons of genuinely experimental television about David Haller, Charles Xavier’s son. Its connection to the films was always deliberately vague. Nothing about Doomsday depends on it — it is on the list because it is the best thing anyone made with these characters on television.',
   intro:'David Haller / Legion, the Shadow King, Syd Barrett'},
  {id:'gifted',t:'The Gifted',y:2017,type:'series',eps:29,run:1247,tier:'optional',tl:9245,tlt:'Earth-10005 (loosely)',dir:'Matt Nix (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Two seasons set in a world where the X-Men have vanished. Solid, conventional, and completely optional. Included so the Fox catalogue is actually complete.',
   intro:'The Mutant Underground, Polaris, Blink, the Strucker family'},
  {id:'xmen97',t:'X-Men ’97',y:2024,type:'series',eps:10,run:330,tier:'recommended',tl:9280,tlt:'Earth-92131',dir:'Beau DeMayo (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'A direct continuation of the 1992 animated series, made by Marvel Studios Animation, and the best-received X-Men project in years. Another universe again — but it is the version of these characters most people carry in their heads.',
   intro:'The animated roster continued, Bastion, Genosha',
   note:'A second season has been announced. This entry covers Season 1 only.'}
]},

{
  no:'Part VI', title:'The Final Run', sub:'Phase 6, 2024–2026',
  blurb:'The last stretch. Everything here was made with Doomsday already on the calendar, and every entry is either directly setting it up or introducing someone confirmed to be in it. Entries marked "Not out yet" carry announced dates that can still move.',
  items:[
  {id:'agatha',t:'Agatha All Along',y:2024,type:'series',eps:9,run:320,tier:'recommended',tl:2026.4,dir:'Jac Schaeffer (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Continues WandaVision and, more importantly, reveals who Billy Maximoff is and where he has been. The Young Avengers assembly is clearly in progress.',
   intro:'Billy Maximoff / Wiccan, Rio Vidal / Death, the Witches’ Road'},
  {id:'bravenewworld',t:'Captain America: Brave New World',y:2025,type:'film',run:118,tier:'recommended',tl:2027,dir:'Julius Onah',where:'Disney+ / JioHotstar (IN)',pc:1,
   why:'Sam’s first film as Captain America, Ross in the presidency, and adamantium introduced to the MCU — a metal that only matters if mutants are coming.',
   intro:'Red Hulk, The Leader, Joaquin Torres / Falcon, Ruth Bat-Seraph, adamantium'},
  {id:'bornagain1',t:'Daredevil: Born Again — Season 1',y:2025,type:'series',eps:9,run:430,tier:'recommended',tl:2027.1,dir:'Dario Scardapane (showrunner)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Fisk as Mayor of New York. The street-level board being reset for whatever comes after Doomsday, with Matt, Frank and Karen all back.',
   intro:'Mayor Fisk, Muse, White Tiger, the anti-vigilante task force'},
  {id:'thunderbolts',t:'Thunderbolts*',y:2025,type:'film',run:127,tier:'essential',tl:2027.2,dir:'Jake Schreier',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Introduces the team most likely to be standing in Doomsday’s front row, and its ending renames them in a way that changes what "the Avengers" even means going in. Its director is also making the 2028 X-Men film.',
   intro:'The Thunderbolts roster, Bob / Sentry, The Void, Valentina in charge'},
  {id:'ironheart',t:'Ironheart',y:2025,type:'series',eps:6,run:290,tier:'optional',tl:2027.3,dir:'Chinaka Hodge (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Riri’s solo run. Its real contribution is putting magic and technology in the same room and introducing Mephisto to the MCU.',
   intro:'Riri Williams, Parker Robbins / The Hood, Mephisto'},
  {id:'ff4',t:'The Fantastic Four: First Steps',y:2025,type:'film',run:114,tier:'essential',tl:9300,tlt:'Earth-828',dir:'Matt Shakman',where:'Disney+ / JioHotstar (IN)',pc:2,
   why:'Marvel’s First Family, from a separate retro-futurist universe. They are central to Doomsday, and Doom’s history with them is the whole reason he is the villain.',
   intro:'Reed, Sue, Johnny, Ben, Franklin Richards, Galactus, Shalla-Bal as the Silver Surfer, Earth-828'},
  {id:'eyesofwakanda',t:'Eyes of Wakanda',y:2025,type:'series',eps:4,run:114,tier:'optional',tl:-3000,tlt:'Ancient Wakanda → 1896',dir:'Todd Harris (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Four animated stories about the Hatut Zaraze, Wakanda’s war dogs, hunting stolen vibranium across centuries of history. It is the deepest look at Wakanda’s past anyone has made, and it costs you under two hours.',
   intro:'The Hatut Zaraze across Wakandan history, vibranium recovered from the wider world',
   note:'All four episodes dropped together on 1 August 2025. The earliest-set entry on this entire list — it opens roughly three thousand years before Iron Man.'},
  {id:'marvelzombies',t:'Marvel Zombies',y:2025,type:'series',eps:4,run:128,tier:'optional',tl:9150,tlt:'Another universe',dir:'Bryan Andrews',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'A spin-off of the What If…? zombie episode, and Marvel Studios Animation’s first TV-MA project. Another universe entirely, so nothing here touches Doomsday — but it is a genuine demonstration of how far a divergent reality can drift, which is the whole idea Doomsday is built on.',
   intro:'The zombie universe expanded, an adult-rated corner of the multiverse',
   note:'All four episodes dropped together on 24 September 2025, and it is roughly two hours end to end. Genuinely violent — the TV-MA rating is not decorative.'},
  {id:'wonderman',t:'Wonder Man',y:2026,type:'series',eps:8,run:225,tier:'optional',tl:2027.4,dir:'Destin Daniel Cretton',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'A Hollywood satire that also brings back Trevor Slattery and introduces Simon Williams — a character with a long comics history alongside Vision.',
   intro:'Simon Williams / Wonder Man, Trevor Slattery returning',
   note:'Released on Disney+ on 27 January 2026, all eight episodes at once. Episodes run 23–34 minutes, the shortest of any MCU series — the whole thing is under four hours.'},
  {id:'bornagain2',t:'Daredevil: Born Again — Season 2',y:2026,type:'series',eps:8,run:389,tier:'optional',tl:2027.5,dir:'Dario Scardapane',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Continues the Fisk arc into 2026. Doomsday relevance stayed modest; included for completeness rather than necessity.',
   intro:'The Fisk arc continued out of Season 1',
   note:'Premiered 24 March 2026 with a two-episode drop, then weekly. Eight episodes averaging just under 49 minutes.'},
  {id:'punisherspecial',t:'The Punisher: One Last Kill',y:2026,type:'special',eps:1,run:51,tier:'optional',tl:2027.6,dir:'Reinaldo Marcus Green',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'A one-off special continuing Frank’s story out of Born Again. Self-contained by design — Frank trying to leave the Punisher behind, and failing.',
   intro:'Frank Castle, post-Born Again',
   note:'Released on Disney+ on 12 May 2026. Jon Bernthal co-wrote it with the director. 51 minutes — the shortest entry on the core list.'},
  {id:'brandnewday',t:'Spider-Man: Brand New Day',y:2026,type:'film',run:145,tier:'essential',tl:2027.7,dir:'Destin Daniel Cretton',where:'Cinemas',pc:1,
   why:'Peter’s first film since the world forgot him, and the last MCU film before Doomsday. Its single post-credits scene points directly at where he turns up next — which makes this the closest thing to a formal prologue Doomsday has.',
   intro:'Peter post-No Way Home, Ned’s Spider-Tracker, Mark Ruffalo’s Hulk',
   note:'Released 31 July 2026 to strong reviews — widely called the best of the MCU Spider-Man films. One post-credits scene, right at the very end of the credits, so stay in your seat. Upgraded from Recommended to Essential now that it has actually landed.'},
  {id:'visionquest',t:'VisionQuest',y:2026,type:'series',eps:8,run:320,tier:'recommended',tl:2027.8,dir:'Terry Matalas (showrunner)',where:'Disney+ / JioHotstar (IN)',pc:0,soon:true,
   why:'White Vision’s story, picking up from WandaVision, and the last announced series before Doomsday. Positioned as a direct lead-in.',
   intro:'White Vision, announced returning cast from WandaVision',
   note:'Announced for Disney+ in late 2026. Episode count and runtime estimated.'},
  {id:'endgameencore',t:'Avengers: Endgame Encore',y:2026,type:'special',eps:1,run:188,tier:'recommended',tl:2027.9,dir:'Anthony and Joe Russo',where:'Cinemas',pc:0,soon:true,
   why:'A theatrical re-release of Endgame recut with several minutes of new footage that lead directly into Doomsday. Deliberately the last thing on this list — it is built to be the final thing you watch before the cinema.',
   intro:'New opening and bonus scenes bridging Endgame to Doomsday',
   note:'Announced for 25 September 2026. If you cannot get to a screening, the original Endgame at the top of this list still covers everything the plot requires — the new footage is a bridge, not a prerequisite. Runtime estimated.'}
]}
];

/* ============ EXTENSIONS — tracked separately, excluded from the core percentage ============ */
var EXTENSIONS = [
{
  no:'Extension A', title:'The Marvel One-Shots', sub:'Five shorts, 2011–2014 · under an hour in total',
  blurb:'Short films released on Phase 1 and 2 Blu-rays, each four to fifteen minutes long. They fill gaps between films rather than advancing anything, but two of them were later picked up by full projects. Where each one slots into the core list is noted on the row.',
  items:[
  {id:'os-consultant',t:'The Consultant',y:2011,type:'short',run:4,tier:'optional',tl:2012.5,dir:'Leythum',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Coulson and Sitwell explain why the World Security Council wanted Emil Blonsky on the Avengers, and how S.H.I.E.L.D. sabotaged it. A footnote to The Incredible Hulk.',
   intro:'The World Security Council’s reach',
   note:'Slots in after The Avengers.'},
  {id:'os-thorshammer',t:'A Funny Thing Happened on the Way to Thor’s Hammer',y:2011,type:'short',run:4,tier:'optional',tl:2011.25,dir:'Leythum',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Coulson stops at a petrol station on his way to New Mexico. Pure charm, zero consequence.',
   intro:'Coulson being Coulson',
   note:'Slots in immediately after Thor.'},
  {id:'os-item47',t:'Item 47',y:2012,type:'short',run:12,tier:'optional',tl:2012.6,dir:'Louis D’Esposito',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'A couple find a leftover Chitauri weapon after the Battle of New York and rob banks with it. The best of the five as a short film in its own right.',
   intro:'Sitwell and Blake, the cleanup after New York',
   note:'Slots in after The Avengers.'},
  {id:'os-agentcarter',t:'Agent Carter',y:2013,type:'short',run:15,tier:'optional',tl:1946,dir:'Louis D’Esposito',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Peggy in 1946, sidelined by the SSR and proving them wrong. This short is what got the Agent Carter series commissioned.',
   intro:'Post-war Peggy, the founding of S.H.I.E.L.D.',
   note:'Slots in after Captain America: The First Avenger.'},
  {id:'os-allhailtheking',t:'All Hail the King',y:2014,type:'short',run:14,tier:'optional',tl:2013.5,dir:'Drew Pearce',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The most consequential of the five. Trevor Slattery in prison, and the reveal that a real Mandarin exists and is not happy — a thread Shang-Chi picked up seven years later.',
   intro:'The real Ten Rings organisation acknowledged',
   note:'Slots in after Iron Man 3. Watch this one if you watch none of the others.'}
]},
{
  no:'Extension B', title:'Sony’s Spider-Man Universe', sub:'Six films, 2018–2024 · not the MCU',
  blurb:'Sony’s own live-action universe built from Spider-Man’s supporting cast, without Spider-Man in it. Venom brushed the MCU twice in post-credits gags and that is the entire connection — Morbius, Madame Web and Kraven have none at all. Listed in full because plenty of people want to watch them, tracked separately because none of it is homework for Doomsday.',
  items:[
  {id:'venom1',t:'Venom',y:2018,type:'film',run:112,tier:'optional',tl:9600,tlt:'Sony universe',dir:'Ruben Fleischer',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:2,
   why:'Tom Hardy’s Eddie Brock, and the film that launched the whole Sony experiment. Broadly enjoyed despite the reviews.',
   intro:'Eddie Brock, the Venom symbiote, Riot'},
  {id:'venom2',t:'Venom: Let There Be Carnage',y:2021,type:'film',run:97,tier:'optional',tl:9601,tlt:'Sony universe',dir:'Andy Serkis',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:1,
   why:'Its mid-credits scene briefly drops Eddie into the MCU, and No Way Home’s own post-credits scene sends him back. That two-minute round trip is the closest these worlds have come.',
   intro:'Cletus Kasady / Carnage, Shriek'},
  {id:'morbius',t:'Morbius',y:2022,type:'film',run:104,tier:'optional',tl:9602,tlt:'Sony universe',dir:'Daniel Espinosa',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:2,
   why:'Notorious rather than good. Its post-credits scenes tried to connect to the MCU through Michael Keaton’s Vulture and never went anywhere.',
   intro:'Michael Morbius, Milo, an unexplained Vulture'},
  {id:'madameweb',t:'Madame Web',y:2024,type:'film',run:116,tier:'optional',tl:9603,tlt:'Sony universe',dir:'S. J. Clarkson',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:0,
   why:'A 2003-set prequel about three future Spider-Women who never become them on screen. Included for completeness.',
   intro:'Cassandra Webb, Julia Cornwall, Mattie Franklin, Anya Corazon'},
  {id:'venom3',t:'Venom: The Last Dance',y:2024,type:'film',run:109,tier:'optional',tl:9604,tlt:'Sony universe',dir:'Kelly Marcel',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:2,
   why:'Closes the Venom trilogy and picks up directly from where No Way Home left Eddie. The most MCU-adjacent film Sony has made.',
   intro:'Knull referenced, the symbiote endgame'},
  {id:'kraven',t:'Kraven the Hunter',y:2024,type:'film',run:127,tier:'optional',tl:9605,tlt:'Sony universe',dir:'J. C. Chandor',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:0,
   why:'The last film Sony released in this universe. No MCU connection at all.',
   intro:'Sergei Kravinoff, the Rhino, the Foreigner'}
]},
{
  no:'Extension C', title:'The Spider-Verse — Miles Morales', sub:'Animated, 2018–2027 · a third continuity again',
  blurb:'Sony Pictures Animation’s trilogy, and by most measures the best Spider-Man films anyone has made. A separate continuity from both the MCU and Sony’s live-action universe, with its own multiverse rules that have nothing to do with Doomsday’s. Watch them because they are extraordinary, not because this list requires it.',
  items:[
  {id:'itsv',t:'Spider-Man: Into the Spider-Verse',y:2018,type:'film',run:117,tier:'optional',tl:9700,tlt:'Earth-1610',dir:'Persichetti, Ramsey and Rothman',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:1,
   why:'Miles Morales’ origin, and the film that reset what animated features could look like. Won the Academy Award for Best Animated Feature.',
   intro:'Miles Morales, Gwen Stacy / Spider-Woman, Peter B. Parker, the Prowler, Kingpin'},
  {id:'atsv',t:'Spider-Man: Across the Spider-Verse',y:2023,type:'film',run:140,tier:'optional',tl:9701,tlt:'Earth-1610',dir:'Dos Santos, Powers and Thompson',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:0,
   why:'The middle chapter, and the one that turns the multiverse into a question about who gets to break the rules. Ends on a hard cliffhanger.',
   intro:'Miguel O’Hara / Spider-Man 2099, the Spider Society, canon events, Spot'},
  {id:'btsv',t:'Spider-Man: Beyond the Spider-Verse',y:2027,type:'film',run:130,tier:'optional',tl:9702,tlt:'Earth-1610',dir:'Sony Pictures Animation',where:'Cinemas',pc:0,soon:true,
   why:'The finale, and the resolution of Across’s cliffhanger. Dated for after Doomsday, so it sits past the finish line — it also appears in the After Doomsday section below.',
   intro:'Announced as the trilogy’s conclusion',
   note:'Announced for 4 June 2027. Runtime estimated. Outside MCU continuity entirely.'}
]},
{
  no:'Extension D', title:'The Marvel Television Era', sub:'The live-action shows the core list skips',
  blurb:'Everything Marvel Television made for Netflix, ABC, Hulu and Freeform that the numbered road leaves out. None of it is required for Doomsday and some of it is genuinely poor, but several are worth an evening on their own terms and a few connect to titles that are on the main list. Tiered by whether they are actually good, not by relevance — because none of them are relevant.',
  items:[
  {id:'jj23',t:'Jessica Jones — Seasons 2 &amp; 3',y:2018,type:'series',eps:26,run:1430,tier:'optional',tl:9800,tlt:'Netflix era',dir:'Melissa Rosenberg (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Season 1 is on the core list; these two are not, because neither reaches it. Season 2 slows to a crawl and Season 3 exists mostly to close the Netflix era down. Completists only.',
   intro:'Trish Walker’s turn, Jessica’s mother, the end of the Netflix run',
   note:'If you liked Season 1 enough to want more Krysten Ritter, Season 3 is the better of the two.'},
  {id:'lukecage',t:'Luke Cage',y:2016,type:'series',eps:26,run:1350,tier:'optional',tl:9801,tlt:'Netflix era',dir:'Cheo Hodari Coker (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Two seasons of Harlem crime drama with the best soundtrack Marvel has ever put on screen. Luke first appears in Jessica Jones Season 1, which is on the core list, so you already have the setup.',
   intro:'Luke Cage, Mariah Dillard, Cottonmouth, Misty Knight, Shades',
   note:'Season 1 front half is superb television; it sags badly after its villain leaves.'},
  {id:'ironfist',t:'Iron Fist',y:2017,type:'series',eps:23,run:1150,tier:'optional',tl:9802,tlt:'Netflix era',dir:'Scott Buck (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The weakest of the Netflix shows by common consent, and the one whose fight choreography most undercuts a series about a martial artist. Season 2 is a clear improvement on Season 1.',
   intro:'Danny Rand, Colleen Wing, Ward and Joy Meachum, K’un-Lun, Davos',
   note:'Watch it only if you intend to watch The Defenders, which assumes you know Danny.'},
  {id:'defenders',t:'The Defenders',y:2017,type:'series',eps:8,run:400,tier:'optional',tl:9803,tlt:'Netflix era',dir:'Douglas Petrie and Marco Ramirez',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The crossover the four Netflix shows were building toward — Daredevil, Jessica Jones, Luke Cage and Iron Fist in one story. Eight episodes, and the shortest way to see that team together.',
   intro:'The four together, Alexandra, the Hand’s endgame, Elektra returned',
   note:'It leans on Daredevil Seasons 1–2 and Iron Fist. Daredevil Season 3 picks up directly from its ending, and Season 3 IS on the core list — this is the gap it quietly assumes.'},
  {id:'agentcarter',t:'Agent Carter',y:2015,type:'series',eps:18,run:780,tier:'optional',tl:9810,tlt:'1946–47',dir:'Markus and McFeely (creators)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Peggy Carter in post-war New York and Los Angeles, founding S.H.I.E.L.D. A lovely period piece and the best-liked thing Marvel Television made. It grew out of the One-Shot in Extension A.',
   intro:'Post-war Peggy, Edwin Jarvis, Howard Stark, the founding of S.H.I.E.L.D.',
   note:'Two seasons, cancelled on a cliffhanger. Watch after Captain America: The First Avenger.'},
  {id:'runaways',t:'Runaways',y:2017,type:'series',eps:33,run:1485,tier:'optional',tl:9811,tlt:'Marvel TV',dir:'Schwartz and Savage (creators)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Six teenagers discover their parents are supervillains. Three seasons on Hulu, and it crosses over with Cloak &amp; Dagger in its third.',
   intro:'The Pride, Molly, Nico, Karolina, Old Lace',
   note:'Faithful to a very well-liked comic, and the only place these characters exist on screen.'},
  {id:'cloakdagger',t:'Cloak &amp; Dagger',y:2018,type:'series',eps:20,run:860,tier:'optional',tl:9812,tlt:'Marvel TV',dir:'Joe Pokaski (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Two seasons on Freeform, set in New Orleans, and better than it had any need to be. Crosses over into Runaways Season 3.',
   intro:'Tyrone Johnson, Tandy Bowen, the Divine Pairing',
   note:'Quietly one of the better Marvel Television shows, and almost nobody watched it.'},
  {id:'inhumans',t:'Inhumans',y:2017,type:'series',eps:8,run:344,tier:'optional',tl:9813,tlt:'Marvel TV',dir:'Scott Buck (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Widely held to be the worst thing Marvel has ever put on screen. It is here because you asked for everything that was skipped, and because Black Bolt appearing in Multiverse of Madness is funnier once you have seen this.',
   intro:'Black Bolt, Medusa, Maximus, Lockjaw, Attilan',
   note:'Eight episodes, cancelled after one season. Go in expecting nothing.'},
  {id:'helstrom',t:'Helstrom',y:2020,type:'series',eps:10,run:480,tier:'optional',tl:9814,tlt:'Marvel TV',dir:'Paul Zbyszewski (creator)',where:'Rent or buy (Prime Video, YouTube, Apple TV)',pc:0,
   why:'The last thing Marvel Television made before the division was folded into Marvel Studios. A horror series about the children of a serial killer, connected to nothing.',
   intro:'Daimon and Ana Helstrom',
   note:'One season, then the whole division closed. Genuinely obscure.'}
]},
{
  no:'Extension E', title:'The Animated Shelf', sub:'Other continuities, none of them required',
  blurb:'Animated Marvel that sits outside every timeline on this site. X-Men ’97 is on the core list because it is a direct continuation with real weight behind it; these are here because they are good, not because Doomsday needs them.',
  items:[
  {id:'xmentas',t:'X-Men: The Animated Series',y:1992,type:'series',eps:76,run:1672,tier:'optional',tl:9820,tlt:'Earth-92131',dir:'Larry Houston and Eric Lewald',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'The show X-Men ’97 continues, five seasons and seventy-six episodes of it. If ’97 on the core list left you wanting the original, this is it — and it is the version of these characters a whole generation carries around.',
   intro:'The 1990s roster, the Phoenix Saga, Days of Future Past, Apocalypse',
   note:'You do not need this to follow X-Men ’97, which recaps what matters. Watch it because it holds up.'},
  {id:'yfnsm',t:'Your Friendly Neighborhood Spider-Man',y:2025,type:'series',eps:10,run:260,tier:'optional',tl:9821,tlt:'Its own continuity',dir:'Jeff Trammell (creator)',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'An animated retelling of Peter’s first year, deliberately separate from the films so it can tell the origin the MCU skipped. Well reviewed, and it stands entirely on its own.',
   intro:'A younger Peter Parker, Norman Osborn as mentor, Nico Minoru',
   note:'Not connected to Holland’s Peter or to the Spider-Verse films. Its own thing.'},
  {id:'whatif23',t:'What If…? — Seasons 2 &amp; 3',y:2023,type:'series',eps:17,run:544,tier:'optional',tl:9822,tlt:'Multiverse',dir:'Bryan Andrews',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Season 1 is on the core list because it establishes the Watcher and how a divergent universe works. These two are variations on that theme — enjoyable, and completely optional.',
   intro:'More Watcher, more divergences, Captain Carter continued',
   note:'Roughly ten hours between them. Season 3 closes the series out.'},
  {id:'iamgroot',t:'I Am Groot',y:2022,type:'series',eps:10,run:50,tier:'optional',tl:9823,tlt:'With the Guardians',dir:'Kirsten Lepore',where:'Disney+ / JioHotstar (IN)',pc:0,
   why:'Ten shorts of Baby Groot causing problems, about five minutes each. No plot consequence whatsoever and none intended.',
   intro:'Baby Groot, and briefly Iwua',
   note:'Under an hour for the whole lot. The lightest thing on this entire site.'}
]}
];


/* Entries with no portrait poster in existence: Wikipedia uses a wordmark for
   TV series. These get a composed one-sheet instead — the official logo on a
   themed field, filling the tile rather than letterboxing inside it. */
var COMPOSED={
  'agentcarter':'#a8253a',
  'cloakdagger':'#3f4a8f',
  'defenders':'#8a5a1f',
  'helstrom':'#6b1f1f',
  'iamgroot':'#4f8f3a',
  'inhumans':'#2f5f8f',
  'ironfist':'#1f7a52',
  'jj23':'#6a2d8f',
  'lukecage':'#c8912a',
  'runaways':'#b0453a',
  'whatif23':'#7a3fb5',
  'xmentas':'#d4a017',
  'yfnsm':'#b0202b',
  'agatha':'#4b2a6b',
  'bornagain1':'#a01018',
  'bornagain2':'#7c0d14',
  'btsv':'#d62b70',
  'dd1':'#b3121d',
  'dd2':'#8f0f18',
  'dd3':'#6d0b12',
  'echo':'#7a1f2b',
  'eyesofwakanda':'#4a2f8f',
  'hawkeye15':'#5a2d82',
  'hawkeye6':'#4a2470',
  'ironheart':'#b0452e',
  'jj1':'#6a2d8f',
  'legion':'#c94f7c',
  'loki1':'#1f7a42',
  'loki2':'#16713a',
  'marvelzombies':'#5a1f1f',
  'moonknight':'#8e93a8',
  'msmarvel':'#1e5aa8',
  'os-consultant':'#2a4a6b',
  'os-thorshammer':'#2a4a6b',
  'pun1':'#3a3f45',
  'pun2':'#2b2f34',
  'secretinvasion':'#2f6b4f',
  'shehulk':'#3f9a4f',
  'tfatws':'#1f4e8c',
  'visionquest':'#8a1f2a',
  'wandavision':'#a51d2a',
  'whatif1':'#7a3fb5',
  'xmen97':'#d4a017'
};

/* Poster art, hotlinked from the Wikipedia article for each title.
   Every URL was verified to serve a real image at build time. A title
   whose image fails to load falls back to a generated card. */
var POSTERS={
  'agentcarter':'https://upload.wikimedia.org/wikipedia/en/1/14/Agent_Carter_%28TV_series%29_logo.png',
  'cloakdagger':'https://upload.wikimedia.org/wikipedia/en/e/ea/Cloak_%26_Dagger_%28TV_series%29_logo.jpg',
  'defenders':'https://upload.wikimedia.org/wikipedia/en/7/72/The_Defenders_%28miniseries%29_logo.jpg',
  'helstrom':'https://upload.wikimedia.org/wikipedia/en/b/b5/Helstrom_%28TV_series%29_logo.jpeg',
  'iamgroot':'https://upload.wikimedia.org/wikipedia/en/f/f7/I_Am_Groot_logo.jpeg',
  'inhumans':'https://upload.wikimedia.org/wikipedia/en/2/2f/Inhumans_%28TV_series%29_logo.jpg',
  'ironfist':'https://upload.wikimedia.org/wikipedia/en/e/eb/Iron_Fist_%28TV_series%29_logo.png',
  'jj23':'https://upload.wikimedia.org/wikipedia/en/2/22/Jessica_Jones_%28TV_series%29_logo.jpg',
  'lukecage':'https://upload.wikimedia.org/wikipedia/en/0/01/Luke_Cage_%28TV_series%29_logo.png',
  'runaways':'https://upload.wikimedia.org/wikipedia/en/2/2d/Runaways_%28TV_series%29_logo.jpg',
  'whatif23':'https://upload.wikimedia.org/wikipedia/en/b/b6/What_If...%3F_%28TV_series%29_logo.png',
  'xmentas':'https://upload.wikimedia.org/wikipedia/en/e/ed/X-Men_The_Animated_Series_logo.jpg',
  'yfnsm':'https://upload.wikimedia.org/wikipedia/en/a/a8/Your_Friendly_Neighborhood_Spider-Man_logo.png',
  'agatha':'https://upload.wikimedia.org/wikipedia/en/7/70/Agatha_All_Along_logo.jpg',
  'antman':'https://upload.wikimedia.org/wikipedia/en/1/12/Ant-Man_%28film%29_poster.jpg',
  'antman2':'https://upload.wikimedia.org/wikipedia/en/2/2c/Ant-Man_and_the_Wasp_poster.jpg',
  'apocalypse':'https://upload.wikimedia.org/wikipedia/en/0/04/X-Men_-_Apocalypse.jpg',
  'atsv':'https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man-_Across_the_Spider-Verse_poster.jpg',
  'avengers':'https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg',
  'blackpanther':'https://upload.wikimedia.org/wikipedia/en/d/d6/Black_Panther_%28film%29_poster.jpg',
  'blackwidow':'https://upload.wikimedia.org/wikipedia/en/e/e9/Black_Widow_%282021_film%29_poster.jpg',
  'blade1':'https://upload.wikimedia.org/wikipedia/en/1/19/Blade_movie.jpg',
  'blade2':'https://upload.wikimedia.org/wikipedia/en/6/6d/Blade_II_movie.jpg',
  'blade3':'https://upload.wikimedia.org/wikipedia/en/8/86/Blade_Trinity_poster.JPG',
  'bornagain1':'https://upload.wikimedia.org/wikipedia/en/d/d9/Daredevil_Born_Again_logo.jpeg',
  'bornagain2':'https://upload.wikimedia.org/wikipedia/en/d/d9/Daredevil_Born_Again_logo.jpeg',
  'brandnewday':'https://upload.wikimedia.org/wikipedia/en/9/9a/Spider-Man_Brand_New_Day_poster.jpg',
  'bravenewworld':'https://upload.wikimedia.org/wikipedia/en/a/a4/Captain_America_Brave_New_World_poster.jpg',
  'btsv':'https://upload.wikimedia.org/wikipedia/en/a/a0/Spider-Man_Beyond_the_Spider-Verse_logo.jpg',
  'captainmarvel':'https://upload.wikimedia.org/wikipedia/en/4/4e/Captain_Marvel_%28film%29_poster.jpg',
  'civilwar':'https://upload.wikimedia.org/wikipedia/en/5/53/Captain_America_Civil_War_poster.jpg',
  'darkphoenix':'https://upload.wikimedia.org/wikipedia/en/9/9e/Dark_Phoenix_%28film%29.png',
  'darkworld':'https://upload.wikimedia.org/wikipedia/en/7/7f/Thor_The_Dark_World_poster.jpg',
  'dd1':'https://upload.wikimedia.org/wikipedia/en/8/8a/Daredevil_%28TV_series%29_logo.jpg',
  'dd2':'https://upload.wikimedia.org/wikipedia/en/8/8a/Daredevil_%28TV_series%29_logo.jpg',
  'dd3':'https://upload.wikimedia.org/wikipedia/en/8/8a/Daredevil_%28TV_series%29_logo.jpg',
  'deadpool1':'https://upload.wikimedia.org/wikipedia/en/2/23/Deadpool_%282016_poster%29.png',
  'deadpool2':'https://upload.wikimedia.org/wikipedia/en/c/cf/Deadpool_2_poster.jpg',
  'dofp':'https://upload.wikimedia.org/wikipedia/en/0/0c/X-Men_Days_of_Future_Past_poster.jpg',
  'dpw':'https://upload.wikimedia.org/wikipedia/en/4/4c/Deadpool_%26_Wolverine_poster.jpg',
  'drstrange':'https://upload.wikimedia.org/wikipedia/en/a/a1/Doctor_Strange_%282016_film%29_poster.jpg',
  'echo':'https://upload.wikimedia.org/wikipedia/en/9/99/Echo_%28miniseries%29_logo.jpg',
  'endgame':'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg',
  'endgameencore':'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg',
  'eternals':'https://upload.wikimedia.org/wikipedia/en/9/9b/Eternals_%28film%29_poster.jpeg',
  'eyesofwakanda':'https://upload.wikimedia.org/wikipedia/en/f/fd/Eyes_of_Wakanda_logo.jpg',
  'farfromhome':'https://upload.wikimedia.org/wikipedia/en/b/bd/Spider-Man_Far_From_Home_poster.jpg',
  'ff4':'https://upload.wikimedia.org/wikipedia/en/1/13/The_Fantastic_Four_First_Steps_poster.jpg',
  'firstavenger':'https://upload.wikimedia.org/wikipedia/en/3/37/Captain_America_The_First_Avenger_poster.jpg',
  'firstclass':'https://upload.wikimedia.org/wikipedia/en/5/55/X-MenFirstClassMoviePoster.jpg',
  'ghostrider1':'https://upload.wikimedia.org/wikipedia/en/7/71/GhostRiderBigPoster.jpg',
  'ghostrider2':'https://upload.wikimedia.org/wikipedia/en/2/2f/Ghost_Rider_2_Poster.jpg',
  'gifted':'https://upload.wikimedia.org/wikipedia/en/3/3f/The_Gifted_Movie_Poster.png',
  'gotg':'https://upload.wikimedia.org/wikipedia/en/3/33/Guardians_of_the_Galaxy_%28film%29_poster.jpg',
  'gotg2':'https://upload.wikimedia.org/wikipedia/en/3/32/Guardians_of_the_Galaxy_Vol._2_poster.jpg',
  'gotg3':'https://upload.wikimedia.org/wikipedia/en/7/74/Guardians_of_the_Galaxy_Vol._3_poster.jpg',
  'hawkeye15':'https://upload.wikimedia.org/wikipedia/en/7/7a/Hawkeye_%28miniseries%29_logo.png',
  'hawkeye6':'https://upload.wikimedia.org/wikipedia/en/7/7a/Hawkeye_%28miniseries%29_logo.png',
  'holidayspecial':'https://upload.wikimedia.org/wikipedia/en/e/e3/The_Guardians_of_the_Galaxy_Holiday_Special_poster.jpg',
  'homecoming':'https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg',
  'hulk':'https://upload.wikimedia.org/wikipedia/en/a/aa/Hulk_%28circa_2019%29.png',
  'infinitywar':'https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg',
  'ironheart':'https://upload.wikimedia.org/wikipedia/en/e/e9/Ironheart_%28miniseries%29_logo.png',
  'ironman':'https://upload.wikimedia.org/wikipedia/en/0/02/Iron_Man_%282008_film%29_poster.jpg',
  'ironman2':'https://upload.wikimedia.org/wikipedia/en/e/ed/Iron_Man_2_poster.jpg',
  'ironman3':'https://upload.wikimedia.org/wikipedia/en/1/19/Iron_Man_3_poster.jpg',
  'itsv':'https://upload.wikimedia.org/wikipedia/en/f/fa/Spider-Man_Into_the_Spider-Verse_poster.png',
  'jj1':'https://upload.wikimedia.org/wikipedia/en/2/22/Jessica_Jones_%28TV_series%29_logo.jpg',
  'kraven':'https://upload.wikimedia.org/wikipedia/en/e/ec/Kraven_the_Hunter_%28film%29_poster.jpg',
  'legion':'https://upload.wikimedia.org/wikipedia/commons/9/97/Legion_TV_series_logo.jpg',
  'logan':'https://upload.wikimedia.org/wikipedia/en/3/37/Logan_2017_poster.jpg',
  'loki1':'https://upload.wikimedia.org/wikipedia/en/4/4e/Loki_%28TV_series%29_logo.png',
  'loki2':'https://upload.wikimedia.org/wikipedia/en/4/4e/Loki_%28TV_series%29_logo.png',
  'lovethunder':'https://upload.wikimedia.org/wikipedia/en/8/88/Thor_Love_and_Thunder_poster.jpeg',
  'madameweb':'https://upload.wikimedia.org/wikipedia/en/f/f0/Madame_Web_%28film%29_poster.jpg',
  'marvels':'https://upload.wikimedia.org/wikipedia/en/7/7a/The_Marvels_poster.jpg',
  'marvelzombies':'https://upload.wikimedia.org/wikipedia/en/1/1a/Marvel_Zombies_%28TV_series%29_logo.png',
  'mom':'https://upload.wikimedia.org/wikipedia/en/1/17/Doctor_Strange_in_the_Multiverse_of_Madness_poster.jpg',
  'moonknight':'https://upload.wikimedia.org/wikipedia/en/a/a8/Moon_Knight_%28miniseries%29_logo.jpg',
  'morbius':'https://upload.wikimedia.org/wikipedia/en/2/2f/Morbius_%28film%29_poster.jpg',
  'msmarvel':'https://upload.wikimedia.org/wikipedia/en/a/ac/Ms._Marvel_%28miniseries%29_logo.jpg',
  'newmutants':'https://upload.wikimedia.org/wikipedia/en/1/1a/TheNewMutantsPoster.jpeg',
  'nowayhome':'https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg',
  'origins':'https://upload.wikimedia.org/wikipedia/en/0/08/X-Men_Origins_Wolverine_theatrical_poster.jpg',
  'os-agentcarter':'https://upload.wikimedia.org/wikipedia/en/a/a7/Agent_Carter_%28film%29_poster.jpg',
  'os-allhailtheking':'https://upload.wikimedia.org/wikipedia/en/9/95/All_Hail_the_King_poster.jpg',
  'os-consultant':'https://upload.wikimedia.org/wikipedia/commons/1/18/Marvel_Studios_One-Shot_logo.png',
  'os-item47':'https://upload.wikimedia.org/wikipedia/en/9/9e/Item_47_poster.jpg',
  'os-thorshammer':'https://upload.wikimedia.org/wikipedia/commons/1/18/Marvel_Studios_One-Shot_logo.png',
  'pun1':'https://upload.wikimedia.org/wikipedia/en/f/fc/Punisher_%28TV_series%29_logo.jpg',
  'pun2':'https://upload.wikimedia.org/wikipedia/en/f/fc/Punisher_%28TV_series%29_logo.jpg',
  'punisherspecial':'https://upload.wikimedia.org/wikipedia/en/a/a0/The_Punisher_One_Last_Kill_poster.jpg',
  'quantumania':'https://upload.wikimedia.org/wikipedia/en/3/30/Ant-Man_and_the_Wasp_Quantumania_poster.jpg',
  'ragnarok':'https://upload.wikimedia.org/wikipedia/en/7/7d/Thor_Ragnarok_poster.jpg',
  'secretinvasion':'https://upload.wikimedia.org/wikipedia/en/9/91/Secret_Invasion_%28miniseries%29_logo.jpg',
  'shangchi':'https://upload.wikimedia.org/wikipedia/en/7/74/Shang-Chi_and_the_Legend_of_the_Ten_Rings_poster.jpeg',
  'shehulk':'https://upload.wikimedia.org/wikipedia/en/3/32/She-Hulk_Attorney_at_Law_logo.jpg',
  'spidey1':'https://upload.wikimedia.org/wikipedia/en/6/6c/Spider-Man_%282002_film%29_poster.jpg',
  'spidey2':'https://upload.wikimedia.org/wikipedia/en/4/4e/Spider-Man_2_USA_poster.jpg',
  'spidey3':'https://upload.wikimedia.org/wikipedia/en/7/7a/Spider-Man_3%2C_International_Poster.jpg',
  'tasm1':'https://upload.wikimedia.org/wikipedia/en/e/e0/The_Amazing_Spider-Man_%28film%29_poster.jpg',
  'tasm2':'https://upload.wikimedia.org/wikipedia/en/2/24/The_Amazing_Spider-Man_2_poster.jpg',
  'tfatws':'https://upload.wikimedia.org/wikipedia/en/9/9a/The_Falcon_and_the_Winter_Soldier_logo.png',
  'thor':'https://upload.wikimedia.org/wikipedia/en/9/95/Thor_%28film%29_poster.jpg',
  'thunderbolts':'https://upload.wikimedia.org/wikipedia/en/9/90/Thunderbolts%2A_poster.jpg',
  'ultron':'https://upload.wikimedia.org/wikipedia/en/f/ff/Avengers_Age_of_Ultron_poster.jpg',
  'venom1':'https://upload.wikimedia.org/wikipedia/en/1/10/Venom_%282018_film%29_poster.png',
  'venom2':'https://upload.wikimedia.org/wikipedia/en/a/a7/Venom_Let_There_Be_Carnage_poster.jpg',
  'venom3':'https://upload.wikimedia.org/wikipedia/en/a/a3/Venom_The_Last_Dance_Poster.jpg',
  'visionquest':'https://upload.wikimedia.org/wikipedia/en/d/d5/VisionQuest_logo.jpg',
  'wakandaforever':'https://upload.wikimedia.org/wikipedia/en/3/3b/Black_Panther_Wakanda_Forever_poster.jpg',
  'wandavision':'https://upload.wikimedia.org/wikipedia/en/2/20/WandaVision_logo.png',
  'werewolf':'https://upload.wikimedia.org/wikipedia/en/0/06/Werewolf_by_Night_%28TV_special%29_poster.jpg',
  'whatif1':'https://upload.wikimedia.org/wikipedia/en/b/b6/What_If...%3F_%28TV_series%29_logo.png',
  'wintersoldier':'https://upload.wikimedia.org/wikipedia/en/9/9e/Captain_America_The_Winter_Soldier_poster.jpg',
  'wolverine2013':'https://upload.wikimedia.org/wikipedia/en/7/74/The_Wolverine_posterUS.jpg',
  'wonderman':'https://upload.wikimedia.org/wikipedia/en/4/44/Wonder_Man_%28Simon_Williams%29.png',
  'x2':'https://upload.wikimedia.org/wikipedia/en/3/3e/X2_poster.jpg',
  'x3':'https://upload.wikimedia.org/wikipedia/en/5/5b/X-Men_The_Last_Stand_theatrical_poster.jpg',
  'xmen1':'https://upload.wikimedia.org/wikipedia/en/8/81/X-MenfilmPoster.jpg',
  'xmen97':'https://upload.wikimedia.org/wikipedia/commons/6/6a/X-Men_%2797_logo.png'
};
